### ISSUE TITLE
account_cryptocurrency : precision issue

### ISSUE THREAD

**Issue by d4e-ch** [OCA/currency#112]
Hello !
First, thanks a lot for those modules.
I have an issue with ETH for examples, which needs 18 decimals.
It gives a precision problem, caused by the `Float` type limitation.

In this account move, I entered **1.0** as unit price. But I have **1.000000000000000222** .
![image](https://user-images.githubusercontent.com/52782157/138036622-8404733d-16ff-403a-b94f-f1ca87f39d3f.png)

How do you do with such issues ?

Thanks a lot !

**Comment by bosd** [comment]
On which version does this occur?

**Comment by d4e-ch** [comment]
Hello,
My tests are on V14.
Thanks,

**Comment by bosd** [comment]
What steps did you take? How to replicate this?

**Comment by bosd** [comment]
related: https://github.com/odoo/odoo/issues/7024

Lots of interresting links in: https://github.com/OCA/l10n-brazil/issues/1634#issuecomment-954227161

**Comment by bosd** [comment]
@d4e-ch Do you still have this problem?
I'm on a freshly build V14 image, developing the Monero module.
Here it's fine..
![image](https://user-images.githubusercontent.com/11499387/172707726-89473c03-03ff-48f5-b53d-cbc09cbb1dce.png)

I did notice a different "feature" on the generated pdf.
But that's a different topic.
![image](https://user-images.githubusercontent.com/11499387/172707907-7e148f88-d796-42b7-a65b-3cedf6d22ad0.png)
