### ISSUE TITLE
[14.0] currency_rate_update translation locked

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/currency#124]
There is currently an alert on weblate blocking translation for this module: https://translation.odoo-community.org/projects/currency-14-0/currency-14-0-currency_rate_update/#alerts

![image](https://user-images.githubusercontent.com/55489873/145600872-c8e44c1c-f709-4546-83f2-05fb62f0a87a.png)

Could someone check everything is correct in translation files?

**Comment by pedrobaeza** [comment]
Unlocked!
