### ISSUE TITLE
Warning on old rates

### ISSUE THREAD

**Issue by alexis-via** [OCA/currency#136]
In the old days, I used to maintain a module called "currency_rate_date_check" (https://github.com/OCA/account-financial-tools/tree/8.0/currency_rate_date_check) that would raise an error when doing a currency conversion with a rate that was too far away from the date requested by the currency conversion. I stopped maintaining this module for some good reasons... but it was long ago and I don't remember exactly the reasons !!! One of the problems of this module was that, as it was raising an error, it was blocking the process executed by the user, so solving the problem was immediately a very high emergency, which is annoying for the support team.

In the last month, on Odoo v14, I faced failures of currency_rate_update on customer installations: the cron failed to update the rates, but nobody was informed about the problem. From my experience, sending notifications by email for such problems is not a solution ; the mail may be considered as spam, it may arrive in the mailbox of an employee that left the company, etc.
As you know, I like warning banners (cf my overdue warning modules https://github.com/OCA/credit-control/tree/14.0/account_invoice_overdue_warn). So my idea is to have a warning banner on the accounting dashboard when the last currency rate is older than 4 days (4 days will be an  ir.config_parameter).

What do you think of this idea ? Do you have a better idea ?
If you think the idea is good, I'll implement the feature as an OCA module.
If you think it's not so good, then I'll develop it as an Akretion community module or add it to my module account_usability (https://github.com/akretion/odoo-usability/tree/14.0/account_usability).

**Comment by alexis-via** [comment]
My idea to display a warning banner on the accounting dashboard was not good: warning banners are for form views, not for kanban views! 
So I'm thinking about the best way to send a message for users that they can't miss. Create an activity ? Send a chat message ?

**Comment by nibraun** [comment]
I think this is a very good idea ;-) The chat message or simply an email...

**Comment by alexis-via** [comment]
Other ideas include:
- using web_notify https://github.com/OCA/web/tree/14.0/web_notify
- using web_environment_ribbon https://github.com/OCA/web/tree/14.0/web_environment_ribbon
- using custom JS code inspired from web_environment_ribbon or web_switch_context_warning (but I would like to avoid having a module with JS code to maintain)

**Comment by alexis-via** [comment]
web_notify with sticky=True seems like a good option for me. The README of the module for v14 says "To work properly, the server must be launched in gevent mode.", but, according to my tests on v14, it works even when the server is NOT in multi-worker mode (for me, gevent requires multi-worker, but I may be wrong).

**Comment by rousseldenis** [comment]
I +1 on this.

One question: do you have already proposed something in Odoo directly as it could be a great feature?

**Comment by alexis-via** [comment]
Dear Denis, 
I'm glad you consider this as important !
OCA is full of great features that should be included in odoo directly... web_notify is another example of such great features that should be in odoo core! :)
But, at the end of the day, if we don't want to wait odoo v19 to have a mecanism to make sure the currency rates used are not too old, I propose my module currency_old_rate_notify to the OCA https://github.com/OCA/currency/pull/137

**Comment by rousseldenis** [comment]
Of course. But making an issue or a PR, even if a bottle in...
