### ISSUE TITLE
Currency rate error with multiple services running at the same time

### ISSUE THREAD

**Issue by ghost** [OCA/currency#14]
**Steps to reproduce**:
- **GIVEN** multicompany enviroment
 **AND** one currency update service for each company
 **AND** each company has the same currencies to update

- **WHEN** services are running

**Current behavior**:
odoo.exceptions.UserError: ("In company XXX, the rate of the main currency (YYY) must be 1.00 (current rate: ZZZ).", '')

I'm already working on fixing this error.

**Comment by pedrobaeza** [comment]
Closing as there's a PR fixing it
