### ISSUE TITLE
Fail to obtain data

### ISSUE THREAD

**Issue by Puhlik77** [OCA/currency#185]
module: currency_rate_update
version: 14.0

**Steps to reproduce**
- Accounting/Configuration/Currency Rate providers/Action/Update Rate Wizard
It works on Windows server 2008 Odoo CE 14.0-20210828, but it doesn't work on Windows Server 2022 Odoo CE 14.0-20230110.
Both servers on the same network. Checked log file, no errors
Error: Currency Rate Provider "European Central Bank" failed to obtain data since 2023-10-27 until 2023-10-27

**Current behavior**

**Expected behavior**

**Comment by abhinavvaidya-tsd** [comment]
@Puhlik77 there must be some logs error on the odoo side, server side or browser which can be shared. Can you check again?

**Comment by Puhlik77** [comment]
Hi,Nothing in console, but odoo.log has some. See attached...Alex

    On Thursday, December 7, 2023 at 08:21:52 a.m. EST, abhinavvaidya-tsd ***@***.***> wrote:  
 
 


@Puhlik77 there must be some logs error on the odoo side, server side or browser which can be shared. Can you check again?

**Comment by abhinavvaidya-tsd** [comment]
There is no attachment, please add

**Comment by Puhlik77** [comment]
See attached...
    On Thursday, December 7, 2023 at 08:51:00 a.m. EST, abhinavvaidya-tsd ***@***.***> wrote:  
 
 


There is no attachment, please add

**Comment by techboterp2020** [comment]
is there any resolution for this issue? I am having the same error. 
Currency Rate Provider "European Central Bank" failed to obtain data since 2024-01-01 until 2024-04-01: 'AED'
