### ISSUE TITLE
[11.0]Update currency does not work

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/currency#24]
Hi,

I'm using this addon for update automatically the currency rates for the currencies that we are using right now: Euro, Dolar and Turkish Lira, this is because the rates are so outdated(2010).

I followed the instructions but I just got update the dollar currency:
![laprueba](https://user-images.githubusercontent.com/5034215/41580803-d990503e-73a4-11e8-90bf-ffe144020ffa.png)

I set `USD` as main currency and checked multi-currencies in options:
![configuracion](https://user-images.githubusercontent.com/5034215/41581119-214d29f0-73a6-11e8-99b0-32c1e6071835.png)

I ran the scheduled action too:
![tarea](https://user-images.githubusercontent.com/5034215/41581054-e81121f0-73a5-11e8-8d19-b7b3fd7b1485.png)

So, what's the problem here?

**Comment by pedrobaeza** [comment]
You have to set the currencies at company level.

**Comment by SalahAdDin** [comment]
I did, I put Turkish lira as the base:
![ahora](https://user-images.githubusercontent.com/5034215/41583482-512b01b8-73ad-11e8-9548-389d23b4e94f.png)

**Comment by pedrobaeza** [comment]
No, that's not what I'm talking about. Please check README.

**Comment by SalahAdDin** [comment]
![this](https://user-images.githubusercontent.com/5034215/41584292-9915ef90-73af-11e8-9e92-f731dc175cc0.png)
This?

I checked it many times, along two days and I still get this behaviour.

It just does not works, my odoo version is `Odoo 11.0-20180122 (Community Edition)`.

**Comment by SalahAdDin** [comment]
@pedrobaeza, I tried.

**Comment by levin222** [comment]
the same to me with the version Odoo 11.0-20180718

**Comment by SalahAdDin** [comment]
@levin222, please review my https://github.com/OCA/currency/pull/27
