### ISSUE TITLE
currency_rate_inverted in invoice line

### ISSUE THREAD

**Issue by BusinessTec** [OCA/currency#26]
Version 11 - it looks like  in case  creating an invoice from scratch using currency marked as inverted the product unit price is incorrect as is calculated in account_invoice.py
Is there any known fix for it?

**Comment by MohsenWaleed** [comment]
I'm facing the same issue and I found that currency conversion in account_invoice.py depend on currency rate field without calling _get_conversion_rate which overrided in currency_rate_inverted module.

 self.price_unit = self.price_unit * currency.with_context(dict(self._context or {}, date=self.invoice_id.date_invoice)).**rate**
