### ISSUE TITLE
can't find support for shared currencies?

### ISSUE THREAD

**Issue by ayushin** [OCA/currency#29]
Hi,

The README says that shared currencies are supported (i.e. company_id is NULL in res_currency_rate), however from what I see in the code is that the update module is always setting company_id to the id of the company the updater is configured for.

The README says there's a functional field to share currencies between the companies, what field is that?

**Comment by pedrobaeza** [comment]
Which module? Which version?

**Comment by ayushin** [comment]
My bad!

currency_rate_update 11.0 (latest)

Expected behaviour for multi-companies with shared currencies (company_id = [null]) is to set company_id to [null] when adding new/updated currency rates. Actual behaviour company_id = company_id of the configured currency_update_service, i.e. currency_rate is only visible for that company.

What am I missing?

**Comment by pedrobaeza** [comment]
The module does nothing with that. Shared currencies are got through res.currency records without company_id field set.

**Comment by ayushin** [comment]
- res_currency model in odoo does not have company_id field
- res_currency_rate does have company_id field

That's what I can see in the database.

The module always creates res_currency_rate with a company_id non-null.

Perhaps I am missing something trivial, how can I configure the currency rates to be shared?

**Comment by pedrobaeza** [comment]
You're right. The `company_id` field + the record rule is on the rate part, but the shared rate with this module is not possible seeing the code. Just configure the same service across companies or contribute with a modification for allowing it.

**Comment by ayushin** [comment]
This does the trick:

diff --git a/currency_rate_update/models/currency_rate_update.py b/currency_rate_update/models/currency_rate_update.py
index dc46592..cc9afcb 100644
--- a/currency_rate_update/models/currency_rate_update.py
+++ b/currency_rate_update/models/currency_rate_update.py
@@ -103,7 +103,7 @@ class CurrencyRateUpdateService(models.Model):
                                           'this service')
     # Link with company
     company_id = fields.Many2one(
-        'res.company', 'Company', required=True,
+        'res.company', 'Company', required=False,
         default=lambda self: self.env['res.company']._company_default_get(
             'currency.rate.update.service'))
     max_delta_days = fields.Integer(

**Comment by pedrobaeza** [comment]
If I don't remember bad, that link is because you configure update services through a one2many field in the company, and thus it requires that field for the inverse name. There should be then another menu (or section in settings) for configuring this shared update services. Do you understand what I mean?

**Comment by ayushin** [comment]
well, manual update works this way (company_id = [null]), but I guess you are talking about automatic update?

**Comment by pedrobaeza** [comment]
Yes, I'm talking about streamlining the process with this module.
