### ISSUE TITLE
Error in Odoo 12, cannot create rate provider

### ISSUE THREAD

**Issue by virtuabart** [OCA/currency#58]
Hello when I install this, the error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: <odoo.models.NewId object at 0x05D87A90>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 980, in __get__
    value = record.env.cache.get(record, self)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.currency.rate.provider(<odoo.models.NewId object at 0x05D87A90>,).available_currency_ids', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 5472, in onchange
    snapshot1 = Snapshot(record, nametree)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 5379, in __init__
    if subnames else record[name]
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 5088, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 986, in __get__
    self.determine_draft_value(record)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 1106, in determine_draft_value
    self._compute_value(record)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 1042, in _compute_value
    getattr(records, self.compute)()
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\currency_rate_update\models\res_currency_rate_provider.py", line 129, in _compute_available_currency_ids
    provider._get_supported_currencies()
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1561, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 4078, in _search
    query = self._where_calc(args)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 3871, in _where_calc
    where_clause, where_params = e.to_sql()
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\osv\expression.py", line 1289, in to_sql
    q, ps = self.__leaf_to_sql(leaf)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\osv\expression.py", line 1231, in __leaf_to_sql
    raise ValueError("Invalid domain term %r" % (leaf,))
ValueError: Invalid domain term ('name', 'in', dict_keys(['AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS', 'AUD', 'AWG', 'AZN', 'BAM', 'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BRL', 'BSD', 'BTC', 'BTN', 'BWP', 'BYN', 'BZD', 'CAD', 'CDF', 'CHF', 'CLF', 'CLP', 'CNH', 'CNY', 'COP', 'CRC', 'CUC', 'CUP', 'CVE', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'ERN', 'ETB', 'EUR', 'FJD', 'FKP', 'GBP', 'GEL', 'GGP', 'GHS', 'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD', 'HNL', 'HRK', 'HTG', 'HUF', 'IDR', 'ILS', 'IMP', 'INR', 'IQD', 'IRR', 'ISK', 'JEP', 'JMD', 'JOD', 'JPY', 'KES', 'KGS', 'KHR', 'KMF', 'KPW', 'KRW', 'KWD', 'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LYD', 'MAD', 'MDL', 'MGA', 'MKD', 'MMK', 'MNT', 'MOP', 'MRO', 'MRU', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR', 'MZN', 'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD', 'OMR', 'PAB', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF', 'SAR', 'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLL', 'SOS', 'SRD', 'SSP', 'STD', 'STN', 'SVC', 'SYP', 'SZL', 'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TRY', 'TTD', 'TWD', 'TZS', 'UAH', 'UGX', 'USD', 'UYU', 'UZS', 'VEF', 'VES', 'VND', 'VUV', 'WST', 'XAF', 'XAG', 'XAU', 'XCD', 'XDR', 'XOF', 'XPD', 'XPF', 'XPT', 'YER', 'ZAR', 'ZMW', 'ZWL']))

**Comment by alexey-pelykh** [comment]
@rockethubble can you reproduce this on clean install or even better - on runbot?

**Comment by carlo-github** [comment]
I have the same problem described above in Odoo12

> 
> 
> Hello when I install this, the error:
> 
> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 1039, in get
> value = self._data[key][field][record._ids[0]]
> KeyError: <odoo.models.NewId object at 0x05D87A90>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 980, in **get**
> value = record.env.cache.get(record, self)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 1041, in get
> raise CacheMiss(record, field)
> odoo.exceptions.CacheMiss: ('res.currency.rate.provider(<odoo.models.NewId object at 0x05D87A90>,).available_currency_ids', None)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 654, in _handle_exception
> return super(JsonRequest, self)._handle_exception(exception)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 312, in _handle_exception
> raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
> raise value
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 696, in dispatch
> result = self._call_function(**self.params)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 344, in _call_function
> return checked_call(self.db, *args, **kwargs)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 97, in wrapper
> return f(dbname, *args, **kwargs)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 337, in checked_call
> result = self.endpoint(*a, **kw)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 939, in **call**
> return self.method(*args, **kw)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 517, in response_wrap
> response = f(*args, **kw)
> File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 962, in call_kw
> return self._call_kw(model, method, args, kwargs)
> File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
> return call_kw(request.env[model], method, args, kwargs)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 749, in call_kw
> return _call_kw_multi(method, model, args, kwargs)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 736, in _call_kw_multi
> result = method(recs, *args, **kwargs)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 5472, in onchange
> snapshot1 = Snapshot(record, nametree)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 5379, in **init**
> if subnames else record[name]
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 5088, in **getitem**
> return self._fields[key].**get**(self, type(self))
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 986, in **get**
> self.determine_draft_value(record)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 1106, in determine_draft_value
> self._compute_value(record)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\fields.py", line 1042, in _compute_value
> getattr(records, self.compute)()
> File "c:\program files (x86)\odoo 12.0\server\odoo\addons\currency_rate_update\models\res_currency_rate_provider.py", line 129, in _compute_available_currency_ids
> provider._get_supported_currencies()
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 1561, in search
> res = self._search(args, offset=offset, limit=limit, order=order, count=count)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 4078, in _search
> query = self._where_calc(args)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\models.py", line 3871, in _where_calc
> where_clause, where_params = e.to_sql()
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\osv\expression.py", line 1289, in to_sql
> q, ps = self.__leaf_to_sql(leaf)
> File "C:\Program Files (x86)\Odoo 12.0\server\odoo\osv\expression.py", line 1231, in __leaf_to_sql
> raise ValueError("Invalid domain term %r" % (leaf,))
> ValueError: Invalid domain term ('name', 'in', dict_keys(['AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS', 'AUD', 'AWG', 'AZN', 'BAM', 'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BRL', 'BSD', 'BTC', 'BTN', 'BWP', 'BYN', 'BZD', 'CAD', 'CDF', 'CHF', 'CLF', 'CLP', 'CNH', 'CNY', 'COP', 'CRC', 'CUC', 'CUP', 'CVE', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'ERN', 'ETB', 'EUR', 'FJD', 'FKP', 'GBP', 'GEL', 'GGP', 'GHS', 'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD', 'HNL', 'HRK', 'HTG', 'HUF', 'IDR', 'ILS', 'IMP', 'INR', 'IQD', 'IRR', 'ISK', 'JEP', 'JMD', 'JOD', 'JPY', 'KES', 'KGS', 'KHR', 'KMF', 'KPW', 'KRW', 'KWD', 'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LYD', 'MAD', 'MDL', 'MGA', 'MKD', 'MMK', 'MNT', 'MOP', 'MRO', 'MRU', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR', 'MZN', 'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD', 'OMR', 'PAB', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF', 'SAR', 'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLL', 'SOS', 'SRD', 'SSP', 'STD', 'STN', 'SVC', 'SYP', 'SZL', 'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TRY', 'TTD', 'TWD', 'TZS', 'UAH', 'UGX', 'USD', 'UYU', 'UZS', 'VEF', 'VES', 'VND', 'VUV', 'WST', 'XAF', 'XAG', 'XAU', 'XCD', 'XDR', 'XOF', 'XPD', 'XPF', 'XPT', 'YER', 'ZAR', 'ZMW', 'ZWL']))

**Comment by alexey-pelykh** [comment]
@carlo-github is it a fresh install or update? Is it random or repeatable? Is in reproducible on runbot?

**Comment by carlo-github** [comment]
Hy
it's a new install of odoo12 and the errors is happen everytime I choose 'OpenExchangeRates.org" as Source Service. I'm sorry I never used runbot..
Thank you.

**Comment by alexey-pelykh** [comment]
Try #59
