### ISSUE TITLE
Import product variant price

### ISSUE THREAD

**Issue by carlo-github** [OCA/currency#65]
I'm tried to import a csv file (here attached) with some informations regarding a product with 1 attribute and 4 attribute value. I added even a column for the variant sell price but I wan't able to import that.. it update the product price and not each variant price with the related price.
Maybe I made something wrong?
Thank you
[import_hosting_test.zip](https://github.com/OCA/currency/files/3497233/import_hosting_test.zip)

**Comment by pedrobaeza** [comment]
This is not the proper repo, and questions must be done on forums or mailing lists, not here.
