### ISSUE TITLE
[12.] module currency_rate_update European Central Bank Update for non EURO companies

### ISSUE THREAD

**Issue by dvrles001** [OCA/currency#70]
Hello all
In Version 12 ECB currency update can only be used if the companies base currency is EUR.
Is there a reasoning for this change from previous versions?

I understand the warning message below but why the removal of the functionality?
('European Central Bank is suitable only for companies with EUR as base currency!', '')

Regards,

**Comment by alexey-pelykh** [comment]
If your company has main currency as USD and you set EUR/XXX exchange rate as USD/XXX exchange rate, what's the point in that? It's an error-prone miss in previous versions

**Comment by dvrles001** [comment]
Was this the OCA team's reasoning behind this?

We use it in version 10 and 11 for various companies with base currencies ZAR and USD.
It works perfectly there?

As long as we define what the base currency is, it works fine. All it needs is the relational rate between the currencies. Considering European union is a major Trade partner for many non-EU organisations it makes sense to use the ECB weighted average daily rate.

Just because it may be human error prone is not enough of a reason to remove it especially since ECB is a global benchmark or is there an error in my reasoning?

**Comment by alexey-pelykh** [comment]
In v11, module did recalculation of the rate to serve the data you're referring to. In other words, in base company currency is USD, and you needed PLN rate from ECB, it provided you with USD-to(reversed)-EUR-to-PLN, which is obscure. This feature may be added as optional, PRs are always welcome.

But the bottom line is: ECB has no official rate to convert USD to PLN. Doing math on top of official rates is not what currency rate provider should do.

**Comment by dvrles001** [comment]
Thank you for that explanation.

To be clear, currently there is no open and free auto-rate update service module in the OCA for companies without either a EURO (from ECB) or USD (from OpenExchangeRates.org) base currency?

What would you recommend as the best way forward, adding this feature or creating a new module to deal specifically with this outside USD or EUR base currency use cases? 

This is for those that don't depend on the currency for advanced or high volume transactions but probably mainly needing weighted average base for reporting and compliance. For advanced or high volume transactions the paid services are more appropriate.

**Comment by alexey-pelykh** [comment]
There's a pending module in #52 that allows to use currency rates from TransferWise (yet that's targeted mostly for companies that already use it) and seems-to-be-abandoned #43 (that uses https://free.currencyconverterapi.com, yet free seems to be very limited and over-populated). I'm open to implement another services if they provide better free access.

**Comment by alexey-pelykh** [comment]
Quick googling shows https://fixer.io/product seems may be a fit, yet I'm not totally aware of your usecase. For other countries we're working on local-specific providers (National Bank of XXX country)

**Comment by Martronic-SA** [comment]
I think a checkbox to enable the inverted calculation and a warning would be good. So we would be able to have the same behavior as in v10 and v11.
That seems correct for example if you are in USD and you want to know EUR exchange rate, then you can take the inverse of EUR to USD right?
And when calculating exchange rate between two other currencies like CHF and USD from EUR, there seems to be a very slight difference (less than 0.0001) but in the very large majority of the cases this is acceptable  especially when we are rounding the amounts to 0.01 in accounting...

**Comment by Martronic-SA** [comment]
I will provide a PR for that.

**Comment by alexey-pelykh** [comment]
@Martronic-SA seems to me that it would worth adding inverse (EUR-to-ZAR and ZAR-to-EUR) into base module w/o option. Yet adding USD-to-EUR-to-PLN and similar double-exchange rates should be in a separate module (or even base), since such approach is applicable for any provider (yet I still doubt that's correct from accounting point of view).

**Comment by Martronic-SA** [comment]
Well the restriction on EUR might be particular to European Central Bank, this is not the case with openexchangerate.

**Comment by alexey-pelykh** [comment]
@Martronic-SA but EUR restriction is only for ECB, OXR provider supplies whatever it can

**Comment by dvrles001** [comment]
@Martronic-SA thanks for working on that PR. All accounting transactions between currencies are based on actual rates paid which always varies from the ECB or any banks daily average. So in my view a daily rate update is not for transaction rates but more a convenience of some basis for internal reporting and updating rates automatically.

@alexey-pelykh I made some inquiries with the South African Reserve bank (our local ECB) about access to or an api for there daily rates (average weighted until 10am) and they don't have this currently even though you can manually download a spreadsheet of the values. I think this will be the issue with most smaller countries and currencies for localisation.

Why ECB is interesting is because it's a Statutory body is that our Tax Authority trusts it only requiring a adjustments at reporting end of period with local actual value.

**Comment by alexey-pelykh** [comment]
@dvrles001 if SARB provides spreadsheets with currency rates - why not to create a module that downloads them and parses? This module does exactly the same - no API, just downloading files and parsing them.

**Comment by alexey-pelykh** [comment]
I've looked at https://www.resbank.co.za/Research/Rates/Pages/SelectedHistoricalExchangeAndInterestRates.aspx and so far I'm quite sure that there's a way to create proper module that would process this data. Maybe not as straightforward as ECB one, yet quite-quite doable
