### ISSUE TITLE
[12] currency_rate_update doesn't update currencies

### ISSUE THREAD

**Issue by ghost** [OCA/currency#77]
Hello,
I have configurated currency_rate_update for updating everidays and I think it´s not working Properly.
![2020-04-16 17_28_05-Odoo](https://user-images.githubusercontent.com/25029267/79475280-c36c4300-8007-11ea-8983-498d646c7ce9.png)
![2020-04-16 17_29_21-Odoo](https://user-images.githubusercontent.com/25029267/79475390-e4cd2f00-8007-11ea-9694-a28c16fb92d3.png)
But it's not updating everiday, only when I do it manually..
![2020-04-16 17_30_18-Tasas monetarias - Odoo](https://user-images.githubusercontent.com/25029267/79475487-05958480-8008-11ea-9ab2-4a1ca648566f.png)
Is this correct?

**Comment by alexey-pelykh** [comment]
Can you reproduce the behaviour in runbot? From screenshots it seems that it should be updating every day.

**Comment by ghost** [comment]
Hello,
Since April 9th is not updating. It should be updated everyday. The last updates are because I ran them manually.

**Comment by alexey-pelykh** [comment]
Not exactly correct. ECB has no rates for April 10th - April 13th including. https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html 
![image](https://user-images.githubusercontent.com/345102/79488845-a8ef9500-801a-11ea-9590-32d9e7f76b55.png)

but why it had not restored getting the data after - that's a question to be investigated.

**Comment by alexey-pelykh** [comment]
Just to confirm we've understood each other correctly - on 14th, 15th module did not fetch any data from ECB?

**Comment by pedrobaeza** [comment]
I remember a maximum delta was put in the module itself for not fetching data if overpassed. Not sure the exact reason for that.

**Comment by alexey-pelykh** [comment]
If I recall correctly, after refactoring that was removed and now there's no such limit. Screenshots show that last successful update was on April 11th, and next sync is scheduled for April 17th, so after April 11th it failed but then there should have been issues. Or there was no data? I wonder how to debug this..

**Comment by pedrobaeza** [comment]
OK, if it was removed, perfect, as I never understood that limitation. There's no way of debugging it unless the issuer provides logs. If not, it should be closed as not reproducible.

**Comment by HaraldPanten** [comment]
Got the same issue.

Rates aren't being updated. Even manually. I tested on runbot and it has the same issue.

In my local environment, log says:

`odoo.addons.currency_rate_update.models.res_currency_rate_provider: Scheduled currency rates update... `

`odoo.addons.currency_rate_update.models.res_currency_rate_provider: Scheduled currency rates update complete.`

But there's something strange for sure. Did you find any reason? THX!

**Comment by HaraldPanten** [comment]
Hi @alexey-pelykh , @gelo-landoo , @pedrobaeza 

Did you find anything strange or any news about that issue?

THX!

**Comment by alexey-pelykh** [comment]
@HaraldPanten I haven't seen such behaviour live, on my instances it works as expected. In this case definitely debugging of your particular instance would be needed, maybe even adding logs to the sources, checking DB entries of those providers. OR this behaviour is reproducible on runbot, but it seems that it isn't.

**Comment by alexey-pelykh** [comment]
Also, I should note that I'm not using ECB provider on my instances, so maybe it's something about that particular provider. Have you tried recreating it or using other one?

**Comment by HaraldPanten** [comment]
Not really. I was using ECB and debbuging it seems to work properly.

Let me try another provider and I'll let you know...

**Comment by pedrobaeza** [comment]
I have it working as well. Check last sucessful update date and next run date.

Closing this meanwhile there are no more evidences.

**Comment by HaraldPanten** [comment]
Hi guys, I found the issue:

If field currency_ids from res.currency.rate.provider model is empty, none of the currencies is being updated.

IMHO it should work like that.

As many others many2many (no mandatory) fields, if the field is empty, it should select all the options. Otherwise, we should make this field mandatory.

If we don't do this small change, user is not getting any "bad feedback" nor "debugging" message that explains why the currency rates are not being updated.

If it's OK for you I'll purpose the PR.

What do you think @pedrobaeza @alexey-pelykh ?

**Comment by pedrobaeza** [comment]
Of course current behavior is something expected IMO, but if you want to clarify it in the README...

**Comment by alexey-pelykh** [comment]
> As many others many2many (no mandatory) fields, if the field is empty, it should select all the options.

That is a bit voodoo magic, IMHO.

**Comment by pedrobaeza** [comment]
Indeed, expecting that all the possible currencies provided by the provider are updated if you leave the field empty is not something desirable.

**Comment by pedrobaeza** [comment]
The field can be made required for better UI.

**Comment by HaraldPanten** [comment]
> The field can be made required for better UI.

That would be the best I think

**Comment by HaraldPanten** [comment]
Is it OK for you if I purpose a small IMP PR? @pedrobaeza @alexey-pelykh ?

**Comment by alexey-pelykh** [comment]
PRs are always welcomed
