### ISSUE TITLE
[Question] currency_rate_update only sync with USD? At least not working with GBP, JPY, DKK

### ISSUE THREAD

**Issue by rafaelbn** [OCA/currency#84]
Hello,

I'm trying to sync USD and GBP, USD works but GBP not.

Any idea?

Thanks in advance
Regards

**Comment by alexey-pelykh** [comment]
@rafaelbn a bit more details would be much appreciated, since it works for me for EUR/USD/AUD/GBP/UAH with EUR as base currency

**Comment by rafaelbn** [comment]
Hello @alexey-pelykh , thanks for answering.

Well we should then look deeper... It just that a normal configuration doesn't work as expected

![2020-09-18_12-01-36](https://user-images.githubusercontent.com/8736623/93585470-25f6b000-f9a7-11ea-81dd-1ff8c8e09eb5.png)

**Comment by alexey-pelykh** [comment]
Is that reproducible on runbot? I'm not using ECB on my instance thus can not verify its behaviour over long period of time

**Comment by victoralmau** [comment]
Related with this issue, i have created https://github.com/OCA/currency/pull/85 that pretend to solved this "special situation" and describe the problem.

**Comment by rafaelbn** [comment]
Closing then, we continue ni https://github.com/OCA/currency/pull/85
