### ISSUE TITLE
[13.0/14.0] currency_rate_update: uses deprecated _company_default_get function

### ISSUE THREAD

**Issue by Yenthe666** [OCA/currency#92]
If you install the module & use it you will notice the following in the logs:

```
2020-12-29 13:29:42,817 42524 WARNING test_db odoo.addons.base.models.res_company: The method '_company_default_get' on res.company is deprecated and shouldn't be used anymore 
```
Which comes back from:
https://github.com/odoo/odoo/blob/de697129d3df2a0ca1f675af1bf57cc5c8a44f5c/odoo/addons/base/models/res_company.py#L180-L187

This should be replaced :)  Just use `self.env.company`

**Comment by alexis-via** [comment]
Fixed in v14 : https://github.com/OCA/currency/blob/14.0/currency_rate_update/models/res_currency_rate_provider.py#L28
and in v13 too https://github.com/OCA/currency/blob/13.0/currency_rate_update/models/res_currency_rate_provider.py#L28

**Comment by alexis-via** [comment]
So we can close the issue... but I don't have enough rights to close this issue (!)
