### ISSUE TITLE
[12.0]currency_rate_update:currencies aren't update 

### ISSUE THREAD

**Issue by chusamo** [OCA/currency#93]
Hello community,
The main currency of one of the companies, is EUR. In that company I have configured the automatization of USD rate. Despite of the fact the last sucesfull date is updated,  the currency rate is not. 

I have checked similars pots like #77 however I can't find the solution yet. Maybe do you know what could be?

Thank you

**Comment by matteoopenf** [comment]
I have the same problem

**Comment by andreinl** [comment]
The problem has a very simple solution: you should change the update hour. It should be before 24:00. Module sets this by default to 01:00 but at this time there is no currency rate for the day and server returns no values.
data.xml file should be changed to set time to something like 21:00 and \<odoo\> tag should be \<odoo noupdate="1"\>

**Comment by pedrobaeza** [comment]
cc @victoralmau

**Comment by matteoopenf** [comment]
> The problem has a very simple solution: you should change the update hour. It should be before 24:00. Module sets this by default to 01:00 but at this time there is no currency rate for the day and server returns no values.
> data.xml file should be changed to set time to something like 21:00 and <odoo> tag should be <odoo noupdate="1">

have you try and it work?

**Comment by andreinl** [comment]
Yes. You can read here: https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html
that "The reference rates are usually updated around 16:00 CET on every working day, except on TARGET closing days.".

Attention, you will need to wait a few days because the function will not run the second time during the same day

**Comment by matteoopenf** [comment]
> Yes. You can read here: https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html
> that "The reference rates are usually updated around 16:00 CET on every working day, except on TARGET closing days.".
> 
> Attention, you will need to wait a few days because the function will not run the second time during the same day

Many thanks for the suggestion

**Comment by alexey-pelykh** [comment]
> The problem has a very simple solution: you should change the update hour. It should be before 24:00. Module sets this by default to 01:00 but at this time there is no currency rate for the day and server returns no values.
data.xml file should be changed to set time to something like 21:00 and <odoo> tag should be <odoo noupdate="1">

Changing time by default to fit one provider is a questionable approach. I believe it was discussed somewhere that eventually the module should enhanced to run cron every hour and rely on provider to mark if the data was fetched for the given day, optionally allowing provider to declare "don't call me earlier than" time.

**Comment by victoralmau** [comment]
> > The problem has a very simple solution: you should change the update hour. It should be before 24:00. Module sets this by default to 01:00 but at this time there is no currency rate for the day and server returns no values.
> > data.xml file should be changed to set time to something like 21:00 and  tag should be
> 
> Changing time by default to fit one provider is a questionable approach. I believe it was discussed somewhere that eventually the module should enhanced to run cron every hour and rely on provider to mark if the data was fetched for the given day, optionally allowing provider to declare "don't call me earlier than" time.

https://github.com/OCA/currency/pull/85

**Comment by alexey-pelykh** [comment]
@victoralmau yes, I'm aware of that PR, but I don't really favor the approach there

**Comment by victoralmau** [comment]
> @victoralmau yes, I'm aware of that PR, but I don't really favor the approach there

Ok, what change do you suggest exactly to avoid that? (Remember that ECB does not return an error if the request is made before 17:00, so the values of `last_successful_run` and `next_run` are changed, which causes no data to be saved).

**Comment by andreinl** [comment]
Anyway setting _noupdate="1"_ is a very simple change and generally correct approach

**Comment by alexey-pelykh** [comment]
that's 100%

**Comment by matteoopenf** [comment]
I have again the problem and cron start at 17.01, have you some news, or there is some changed?
https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml If I call from browser it works from code it's seems empty
